enabled_rules:
    - attributes
    - class_delegate_protocol
    - colon
    - comma
    - control_statement
    - closure_parameter_position
    - closure_end_indentation
    - closure_spacing
    - closing_brace
    - conditional_returns_on_newline
    - custom_rules
    - discarded_notification_center_observer
    - dynamic_inline
    - empty_count
    - empty_enum_arguments
    - empty_parameters
    - empty_parentheses_with_trailing_closure
    - explicit_top_level_acl
    - explicit_type_interface
    - fatal_error_message
    - first_where
    - force_cast
    - force_try
    - for_where
    - identifier_name
    - implicit_getter
    - implicit_return
    - implicitly_unwrapped_optional
    - generic_type_name
    - large_tuple
    - leading_whitespace
    - legacy_cggeometry_functions
    - legacy_constant
    - legacy_constructor
    - legacy_nsgeometry_functions
    - mark
    - multiline_parameters
    - nimble_operator
    - nesting
    - notification_center_detachment
    - no_extension_access_modifier
    - opening_brace
    - operator_usage_whitespace
    - operator_whitespace
    - object_literal
    - overridden_super_call
    - private_unit_test
    - private_outlet
    - prohibited_super_call
    - protocol_property_accessors_order
    - redundant_discardable_let
    - redundant_optional_initialization
    - redundant_string_enum_value
    - redundant_nil_coalescing
    - redundant_void_return
    - return_arrow_whitespace
    - shorthand_operator
    - statement_position
    - sorted_imports
    - switch_case_on_newline
    - trailing_comma
    - trailing_newline
    - trailing_semicolon
    - trailing_whitespace
    - todo
    - unused_enumerated
    - unused_optional_binding
    - unused_closure_parameter
    - valid_ibinspectable
    - vertical_whitespace
    - weak_delegate
    - void_return
    - vertical_parameter_alignment
    - vertical_parameter_alignment_on_call
disabled_rules:
    - compiler_protocol_init
    - cyclomatic_complexity # counts ifs
    - extension_access_modifier
    - explicit_init
    - file_length
    - function_body_length
    - function_parameter_count
    - line_length
    - number_separator
    - syntactic_sugar
    - type_body_length
    - type_name
trailing_whitespace: 
    ignores_empty_lines: true
    