disabled_rules:
    - class_delegate_protocol
    - closing_brace
    - colon
    - comma
    - control_statement
    - closure_parameter_position
    - compiler_protocol_init
    - custom_rules
    - cyclomatic_complexity
    - discarded_notification_center_observer
    - dynamic_inline
    - empty_enum_arguments
    - empty_parameters
    - empty_parentheses_with_trailing_closure
    - file_length
    - for_where
    - force_cast
    - force_try
    - function_body_length
    - identifier_name
    - function_parameter_count
    - generic_type_name
    - implicit_getter
    - large_tuple
    - leading_whitespace
    - legacy_cggeometry_functions
    - legacy_constant
    - legacy_constructor
    - legacy_nsgeometry_functions
    - line_length
    - mark
    - nesting
    - notification_center_detachment
    - opening_brace
    - operator_whitespace
    - private_unit_test
    - protocol_property_accessors_order
    - redundant_discardable_let
    - redundant_optional_initialization
    - redundant_string_enum_value
    - redundant_void_return
    - return_arrow_whitespace
    - shorthand_operator
    - statement_position
    - syntactic_sugar
    - trailing_comma
    - trailing_newline
    - trailing_semicolon
    - trailing_whitespace
    - type_body_length
    - type_name
    - todo
    - unused_closure_parameter
    - unused_enumerated
    - unused_optional_binding
    - valid_ibinspectable
    - vertical_parameter_alignment
    - vertical_whitespace
    - void_return
    - weak_delegate